[package]
name = "bitwarden-vault"
description = """
Internal crate for the bitwarden crate. Do not use.
"""

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license = "GPL-3.0-only OR LicenseRef-Bitwarden-SDK"
keywords.workspace = true

[features]
uniffi = [
    "bitwarden-collections/uniffi",
    "bitwarden-core/uniffi",
    "bitwarden-crypto/uniffi",
    "dep:uniffi",
] # Uniffi bindings
wasm = [
    "bitwarden-collections/wasm",
    "bitwarden-core/wasm",
    "bitwarden-encoding/wasm",
    "bitwarden-state/wasm",
    "dep:tsify",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
] # WASM support

[dependencies]
async-trait = { workspace = true }
bitwarden-api-api = { workspace = true }
bitwarden-api-base = { workspace = true }
bitwarden-collections = { workspace = true }
bitwarden-core = { workspace = true, features = ["internal"] }
bitwarden-crypto = { workspace = true }
bitwarden-encoding = { workspace = true }
bitwarden-error = { workspace = true }
bitwarden-logging = { workspace = true }
bitwarden-ssh = { workspace = true }
bitwarden-state = { workspace = true }
bitwarden-sync = { workspace = true }
bitwarden-uuid = { workspace = true }
chrono = { workspace = true }
data-encoding = { workspace = true }
futures = { workspace = true }
hmac = { workspace = true }
percent-encoding = ">=2.1, <3.0"
reqwest = { workspace = true, features = ["stream", "multipart"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
tokio-util = { version = "0.7.15", features = ["io"] }
tracing = { workspace = true }
tsify = { workspace = true, optional = true }
uniffi = { workspace = true, optional = true }
uuid = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
zeroize = { workspace = true, features = ["derive"] }
zxcvbn = { workspace = true }

[dev-dependencies]
bitwarden-api-api = { workspace = true, features = ["mockall"] }
bitwarden-core = { workspace = true, features = ["internal", "test-fixtures"] }
bitwarden-test = { workspace = true }
static_assertions = "1.1.0"
tokio = { workspace = true, features = ["rt"] }
wiremock = { workspace = true }

[lints]
workspace = true
